### ISSUE TITLE
Usage check of view models methods in ZUL files

### ISSUE THREAD

**Issue by vbonnefon** [zkoss/zkidea#35]
I don't know if this is a configuration problem on my side, but all ViewModels acessors, or @commands methods that are only used in the ZUL files are reported as "unused" by the IDE.
Also, when trying top inspect usage or refactor a method, ZUL usage are never included.
Is there a configuration to tell the plugin where the ZUL files are or is it just a limitation of the pluggin ?

**Comment by hawkchen** [comment]
Do you mean this warning "..method is never used"?
![neverUsed](https://github.com/zkoss/zkidea/assets/1088642/cc3391ba-8945-4973-9b18-f02ca5167e18)

It's generated by IntelliJ IDEA, not by zk plugin. Since it's never called by any Java method. IDEA doesn't treat data binding on a zul as a java method calling. You can configure IDEA to suppress this warning.
