### ISSUE TITLE
Version 1.20 enabled/disable bug

### ISSUE THREAD

**Issue by ginalpisti** [zkoss/zkidea#39]
We noticed that the latest version (1.20) with the latest IntelliJ IDEA (2023.2.1) has an issue.
Starting the IDE shows the plugin enabled, but it does not seem to work az expected. Disabling and reenabling it solves the issue temporarily. After an IDE restart the problem reemerges.

**Comment by jumperchen** [comment]
Do you have any error logs for us to clarify this issue?
And which environment are you using?

**Comment by damgel** [comment]
I have the same problem. Its happening on Windows 10 and 11(have two coding laptops). The problem doesnt generate any warning, error or logs when opening the IDE.

The problem is present under this versions:
IntelliJ IDEA 2023.2.1(reported it on Jetbrains Marketplace) 
IntelliJ IDEA 2023.2.2 (upgraded today and problem persists).

IntelliJ IDEA 2023.2.2 RC (Ultimate Edition)
Build #IU-232.9921.28, built on September 6, 2023
Runtime version: 17.0.8+7-b1000.22 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Registry:
    debugger.new.tool.window.layout=true
    ide.experimental.ui=true
    ide.images.show.chessboard=true

Non-Bundled Plugins:
    org.zkoss.zkidea (0.1.20)

Kotlin: 232-1.9.0-IJ9921.28


The only relevant information related to the plugin in the **idea.log** : 

2023-09-09 10:06:47,351 [  11429]   INFO - #c.i.s.p.SettingsSyncPluginManager - Updated component state by the state of IDE.
No changes: {0537=PluginData(org.zkoss.zkidea=PluginData(enabled=true, category=PLUGINS, dependencies=[org.jetbrains.idea.maven, com.intellij.modules.java])}

**Comment by jumperchen** [comment]
@damgel Thanks for the info., I can reproduce this on Windows 10 environment only. Here is a workaround to set File Types mapping with **.zul* file.
For example,
1. Settings -> Editor -> File Types -> XML
2. add **.zul* as new File name patterns

**Comment by damgel** [comment]
> * or -> File Types -> XML

Great!. That solved the problem!. 

Thanks for your help @jumperchen

**Comment by jumperchen** [comment]
Add Intellij issue tracker here for someone who wants to follow up - https://youtrack.jetbrains.com/issue/IDEA-332030
